### ISSUE TITLE
auto-generated TOC like datatracker.ietf.org

### ISSUE THREAD

**Issue by pspacek** [icann/icann-annotations#8]
Hello once again,

I have a second usability request, this time larger one.
Over time I've noticed that I often resort to datatracker.ietf.org HTMLized version because it has better hyperlinks. E.g. for https://datatracker.ietf.org/doc/html/rfc1035 the right-hand-side pane of contents is very useful because the document is a beast.

For example navigating from https://rfc-annotations.research.icann.org/rfc1035.html#line-77 to page 25 is tedious.

Thank you for considering this.

**Comment by paulehoffman** [comment]
This seems like a reasonable addition for a future version.
